In [0]:
# This program predicts the Stock Market Price using machine learning.
# import dependencies
import numpy as np 
'''
import the entire numpy module with a short name "np". 
This enables us to work with all the functions present in the module.
NumPy is a general-purpose array-processing package. 
It provides a high-performance multidimensional array 
object, and tools for working with these arrays.
'''
import pandas as pd
'''
import the entire pandas module with a short name "pd". 
This enables us to work with all the functions present in the module.
pandas is a fast, powerful, flexible and easy to use open 
source data analysis and manipulation tool
'''
from sklearn.model_selection import train_test_split
'''
Splits arrays or matrices into random train and test subsets.
'''
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression

In [3]:
# getting the data file
df = pd.read_excel('engro.xlsx')
# printing data
print(df.head())
# the ".head" prints only first 5 data 

   Unnamed: 0 <TICKER>               <DATE>  ...     <LOW>   <CLOSE>      <VOL>
0           1  KSE-100  2015-01-01 00:00:00  ...  32134.53  32480.35  186250880
1           2  KSE-100  2015-02-01 00:00:00  ...  32465.35  32731.61  235201230
2           3  KSE-100  2015-05-01 00:00:00  ...  32663.32  32757.79  248960940
3           4  KSE-100  2015-06-01 00:00:00  ...  32558.31  32668.73  173641810
4           5  KSE-100  2015-07-01 00:00:00  ...  32639.80  32835.95  175312820

[5 rows x 8 columns]


In [4]:
# printing only <CLOSE> column
df = df[['<CLOSE>']]
print(df.tail())
# the ".tail" prints only last 5 data 

      <CLOSE>
741  39470.89
742  39525.75
743  40146.73
744  40371.31
745  40471.48


In [5]:
# A variable for predicting 'n' days out into the future
forecast_out=1
# Create another column (the target or dependent variable) shifted 'n' units up
df['PREDICTION'] = df[['<CLOSE>']].shift(-1)
# print the new data set
print(df.head())

    <CLOSE>  PREDICTION
0  32480.35    32731.61
1  32731.61    32757.79
2  32757.79    32668.73
3  32668.73    32835.95
4  32835.95    33117.47


In [6]:
# print the new data set
print(df.tail())

      <CLOSE>  PREDICTION
741  39470.89    39525.75
742  39525.75    40146.73
743  40146.73    40371.31
744  40371.31    40471.48
745  40471.48         NaN


In [7]:
# A variable for predicting 'n' days out into the future
forecast_out=30
# Create another column (the target or dependent variable) shifted 'n' units up
df['PREDICTION'] = df[['<CLOSE>']].shift(-forecast_out)
# print the new data set
print(df.tail())

      <CLOSE>  PREDICTION
741  39470.89         NaN
742  39525.75         NaN
743  40146.73         NaN
744  40371.31         NaN
745  40471.48         NaN


In [8]:
# print the new data set
print(df.head())

    <CLOSE>  PREDICTION
0  32480.35    33943.20
1  32731.61    33796.44
2  32757.79    33801.11
3  32668.73    33718.86
4  32835.95    33942.28


In [9]:
# Create the independent data set (X) 
# Convert the dataframe to a numpy array
X = np.array(df.drop(['PREDICTION'],1))
#Remove the last 'n' rows
X = X[:-forecast_out]
print(X)

[[32480.35]
 [32731.61]
 [32757.79]
 [32668.73]
 [32835.95]
 [33117.47]
 [33324.82]
 [33418.2 ]
 [33371.29]
 [33585.75]
 [33765.61]
 [33786.44]
 [34014.26]
 [34121.3 ]
 [34329.5 ]
 [34146.97]
 [34026.59]
 [34466.53]
 [34538.45]
 [34386.86]
 [34408.74]
 [34443.87]
 [34676.31]
 [34826.51]
 [34672.25]
 [34656.94]
 [34570.3 ]
 [34432.89]
 [34203.99]
 [33786.42]
 [33943.2 ]
 [33796.44]
 [33801.11]
 [33718.86]
 [33942.28]
 [33993.  ]
 [33926.7 ]
 [33895.46]
 [33845.3 ]
 [33762.8 ]
 [33632.19]
 [33213.58]
 [33188.77]
 [33242.95]
 [33368.84]
 [33263.66]
 [32860.57]
 [32566.59]
 [32539.61]
 [32582.68]
 [32929.09]
 [32454.91]
 [32342.26]
 [31524.98]
 [31451.62]
 [31800.26]
 [31310.73]
 [31086.51]
 [30678.97]
 [29957.83]
 [28927.04]
 [30233.87]
 [30605.06]
 [31132.25]
 [31413.96]
 [31752.17]
 [31600.73]
 [31887.3 ]
 [32013.91]
 [32350.93]
 [32248.45]
 [32109.87]
 [32248.86]
 [32736.44]
 [33234.73]
 [33304.64]
 [33035.77]
 [33490.65]
 [33456.74]
 [33775.12]
 [33844.3 ]
 [33575.94]
 [33460.01]
 [33

In [10]:
# Create the independent data set (X) 
# Convert the dataframe to a numpy array
X = np.array(df['<CLOSE>'])
#Remove the last 'n' rows
X = X[:-forecast_out]
print(X)

[32480.35 32731.61 32757.79 32668.73 32835.95 33117.47 33324.82 33418.2
 33371.29 33585.75 33765.61 33786.44 34014.26 34121.3  34329.5  34146.97
 34026.59 34466.53 34538.45 34386.86 34408.74 34443.87 34676.31 34826.51
 34672.25 34656.94 34570.3  34432.89 34203.99 33786.42 33943.2  33796.44
 33801.11 33718.86 33942.28 33993.   33926.7  33895.46 33845.3  33762.8
 33632.19 33213.58 33188.77 33242.95 33368.84 33263.66 32860.57 32566.59
 32539.61 32582.68 32929.09 32454.91 32342.26 31524.98 31451.62 31800.26
 31310.73 31086.51 30678.97 29957.83 28927.04 30233.87 30605.06 31132.25
 31413.96 31752.17 31600.73 31887.3  32013.91 32350.93 32248.45 32109.87
 32248.86 32736.44 33234.73 33304.64 33035.77 33490.65 33456.74 33775.12
 33844.3  33575.94 33460.01 33729.96 33723.53 33533.64 33839.28 33742.88
 33530.3  32506.36 33023.8  32915.44 33103.73 33039.2  32886.06 32729.55
 32599.   32617.74 32605.62 32707.22 32510.35 32842.59 32763.48 33056.79
 33563.38 33895.34 33908.62 34085.74 34012.49 34151.1

In [11]:
# Create the dependent data set (y)  
# Convert the dataframe to a numpy array (All of the values including the NaN's)
y = np.array(df['PREDICTION'])
# Get all of the y values except the last 'n' rows
y = y[:-forecast_out]
print(y)

[33943.2  33796.44 33801.11 33718.86 33942.28 33993.   33926.7  33895.46
 33845.3  33762.8  33632.19 33213.58 33188.77 33242.95 33368.84 33263.66
 32860.57 32566.59 32539.61 32582.68 32929.09 32454.91 32342.26 31524.98
 31451.62 31800.26 31310.73 31086.51 30678.97 29957.83 28927.04 30233.87
 30605.06 31132.25 31413.96 31752.17 31600.73 31887.3  32013.91 32350.93
 32248.45 32109.87 32248.86 32736.44 33234.73 33304.64 33035.77 33490.65
 33456.74 33775.12 33844.3  33575.94 33460.01 33729.96 33723.53 33533.64
 33839.28 33742.88 33530.3  32506.36 33023.8  32915.44 33103.73 33039.2
 32886.06 32729.55 32599.   32617.74 32605.62 32707.22 32510.35 32842.59
 32763.48 33056.79 33563.38 33895.34 33908.62 34085.74 34012.49 34151.11
 34270.28 34323.84 34594.7  34651.29 34710.29 34516.3  34482.   34674.61
 34526.7  34278.42 34133.84 34331.94 34077.92 33885.13 34093.55 34398.86
 34843.61 35186.56 35456.35 35502.28 35537.69 35328.83 35147.13 35112.29
 35496.62 35446.89 35699.75 35887.66 36056.68 35934.

In [15]:
# Create the independent data set (X) 
# Convert the dataframe to a numpy array
X = np.array(df.drop(['PREDICTION'],1))
#Remove the last 'n' rows
X = X[:-forecast_out]
print(X)

[[32480.35]
 [32731.61]
 [32757.79]
 [32668.73]
 [32835.95]
 [33117.47]
 [33324.82]
 [33418.2 ]
 [33371.29]
 [33585.75]
 [33765.61]
 [33786.44]
 [34014.26]
 [34121.3 ]
 [34329.5 ]
 [34146.97]
 [34026.59]
 [34466.53]
 [34538.45]
 [34386.86]
 [34408.74]
 [34443.87]
 [34676.31]
 [34826.51]
 [34672.25]
 [34656.94]
 [34570.3 ]
 [34432.89]
 [34203.99]
 [33786.42]
 [33943.2 ]
 [33796.44]
 [33801.11]
 [33718.86]
 [33942.28]
 [33993.  ]
 [33926.7 ]
 [33895.46]
 [33845.3 ]
 [33762.8 ]
 [33632.19]
 [33213.58]
 [33188.77]
 [33242.95]
 [33368.84]
 [33263.66]
 [32860.57]
 [32566.59]
 [32539.61]
 [32582.68]
 [32929.09]
 [32454.91]
 [32342.26]
 [31524.98]
 [31451.62]
 [31800.26]
 [31310.73]
 [31086.51]
 [30678.97]
 [29957.83]
 [28927.04]
 [30233.87]
 [30605.06]
 [31132.25]
 [31413.96]
 [31752.17]
 [31600.73]
 [31887.3 ]
 [32013.91]
 [32350.93]
 [32248.45]
 [32109.87]
 [32248.86]
 [32736.44]
 [33234.73]
 [33304.64]
 [33035.77]
 [33490.65]
 [33456.74]
 [33775.12]
 [33844.3 ]
 [33575.94]
 [33460.01]
 [33

In [0]:
# Split the data into 80% training and 20% testing
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [17]:
# Create and train the Support Vector Machine (Regressor)
svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.1)
svr_rbf.fit(x_train, y_train)

SVR(C=1000.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=0.1,
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [21]:
# Testing Model: Score returns the coefficient of determination R^2 of the prediction. 
# The best possible score is 1.0
svm_confidence = svr_rbf.score(x_test, y_test)
print("svm confidence: ", svm_confidence)

svm confidence:  0.06408525170040646


In [22]:
# Create and train the Linear Regression  Model
lr = LinearRegression()
# Train the model
lr.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [23]:
# Testing Model: Score returns the coefficient of determination R^2 of the prediction. 
# The best possible score is 1.0
lr_confidence = lr.score(x_test, y_test)
print("lr confidence: ", lr_confidence)

lr confidence:  0.8397461500151596


In [25]:
# Set x_forecast equal to the last 30 rows of the original data set from Adj. Close column
x_forecast = np.array(df.drop(['PREDICTION'],1))[-forecast_out:]
print(x_forecast)

[[40813.31]
 [40844.4 ]
 [40316.93]
 [40548.83]
 [40591.87]
 [40266.21]
 [40248.41]
 [40032.17]
 [39634.13]
 [39672.89]
 [40010.36]
 [40049.8 ]
 [39945.41]
 [39907.32]
 [38784.66]
 [39080.  ]
 [38481.7 ]
 [38525.11]
 [38819.65]
 [38223.55]
 [38645.9 ]
 [38383.97]
 [37919.42]
 [38208.06]
 [38715.77]
 [39470.89]
 [39525.75]
 [40146.73]
 [40371.31]
 [40471.48]]


In [26]:
# Print linear regression model predictions for the next 'n' days
lr_prediction = lr.predict(x_forecast)
print(lr_prediction)

# Print support vector regressor model predictions for the next 'n' days
svm_prediction = svr_rbf.predict(x_forecast)
print(svm_prediction)

[40817.64536972 40845.79781949 40368.16601884 40578.15486099
 40617.12821057 40322.23831693 40306.12015655 40110.31167347
 39749.88063108 39784.97837804 40090.56239944 40126.27589635
 40031.74922437 39997.25817221 38980.67312032 39248.10781045
 38706.33840873 38745.64679871 39012.35707714 38472.5798076
 38855.02391059 38617.84246416 38197.18564389 38458.55338601
 38918.29221762 39602.06442326 39651.74095573 40214.04742921
 40417.40790429 40508.11330454]
[38966.8745765  38969.83717063 38964.99820339 38974.11525762
 38966.8745765  38966.8745765  38966.88180528 39728.76959261
 38966.8745765  38967.05291326 38966.87468598 39953.27785839
 38966.8745765  39956.6868268  38967.96666137 38966.8745765
 38966.8749545  38966.8745765  38966.8745765  38966.87457755
 38966.8745765  38966.8745765  38966.8745765  38966.8745765
 38966.8745765  39743.12583374 39356.53095851 38966.94203486
 38969.83717063 38966.89156388]
